#Ch04 연습문제

##문제 1
다음에 보인 리스트, `lst`에서 두 번째 요소와 마지막 요소를 출력 하는 `print()` 문을 완성하시오. (`print()` 한번 만 사용)

```python
lst = ['구숙정', '오천련', '매염방', '왕조현', '관지림']
print( )
```

##문제 2
다음 리스트, `lst`의 첫번째 요소는 문자열입니다. `lst`의 첫번째 요소인 문자열 데이터의 마지막 글자를 추출하는 코드를 작성하세요.

```pyton
lst = ['구숙정', 1968, '오천련', 1968, '한예슬', 1981]
```

## 문제 3
다음 리스트, `lst`에서 두 번째 요소의 두 번째 요소는 `'b'`입니다. `lst`에서 두 번째 요소의 두 번째 요소를 추출하여 추력하는 코드를 완성하세요.

```python
lst = ['a', ['a', 'b', 'c'], 'b', ['b', 'c', 'd'], 'c', ['c', 'd', 'e'] ]

print()
```

## 문제 4
아래 코드에 보인 리스트 `a`와 `b`를 활용하여 리스트 `rlst = [1, 2, 3, 1, 2, 3, 4, 5, 4, 5, 4, 5]`가 되도록 코드를 작성하시오.

```python
a = [1, 2, 3, ]
b = [4, 5, ]
```

##문제 5
아래 코드에 보인 `a`, `b`, `c`를 활용하여 문자열 데이터 `'She is a beautiful girl'`를 만들어 출력하는 코드를 작성하시오.

```python
a = ['She', 'is', 'a' ]
b = 'beautiful'
c = ['gril']
```

## 문제 6
아래 코드에 보인 a, b, c를 활용하여 리스트, `lst = ['She', 'is', 'a', 'beautiful' ,'girl']`를 만들어 출력하는 코드를 작성하시오.



```python
a = ['She', 'is', 'a' ]
b = 'beautiful'
c = ['gril']
```

##문제 7
아래와 같이 3명에 대한 정보가 담긴 메시지를 받았습니다.
```python
'김성필, 남, 50, 경기도 화성시 동탄, 010-9105-0000\n구숙정, 여, 35, 경기도 용인시, 010-9105-1111\n주성치, 남, 32, 경기도 수원시, 010-1111-2222'
```

주성치의 주소를 출력하는 코드를 작성하세요.

##문제 8
다음 리스트를 활용하여 아래와 같이 출력되도록 코드를 완성하시오.
```python
lst = ['홍길동', '남', 1973, '경기도 화성시']
```

```
홍길동은 남성으로 1973년 생이며 주소는 경기도 화성시입니다.
```

## 문제 9
아래 코드를 활용합니다. 리스트, `lst`의 요소가 문자열이면 해당 요소에 '님'을 붙이고 해당 요소가 문자열이 아닌 경우 해당 요소 값에 1을 증가 시켜 새로운 리스트, `rlst`를 생성하는 코드를 작성하시오.

```python
lst = ['홍길동', '전우치', 25, 32]
rlst = ['홍길동님', '전우치님', 26, 33]
```

## 문제 10
친구에게 주고 싶어서 과일 가게에서 몇 가지 샀습니다. '사과', '수박', '참외', '딸기'를 샀습니다. 검은 포장지로 싸서 무엇을 샀는지 친구가 보고 알수없습니다. 친구에게 "여기에 들어 있는 것을 맞춰보라고 할 생각입니다"

```python
lst = ['사과', '수박', '참외', '딸기']

name = input('오다가 과일 가게에서 몇 가지 샀어.\n여기에 무엇이 들어있을까? : ')

if (친구가 입력한 것이 구입한 목록에 있다):
  print("어떻게 알았지? ㅎㅎㅎ")
else: # 친구가 맞추지 못하면
  print(lst)
```

위 코드가 실행될 수 있도록 적절히 **한 줄만** 수정하세요.

##문제 11
아래 코드에 보인 `lst`의 모든 요소를 다음과 같이 출력하는 코드를 작성하시오.

```python
lst = [ [1, 2, 3], [ 4, 5, 6] ]
```

출력 결과  

<center>

![image.png]()

</center>

##문제 12
아래 보인 리스트, `dan`을 활용하여 출력 결과가 아래와 같이 나오도록 코드를 작성하시오.
```python
dan = list(range(2, 9))
```
출력 결과   
<center>

![image.png]()

</center>

##문제 13
아래 보인 리스트, `dan`을 활용하여 출력 결과가 아래와 같이 나오도록 코드를 작성하시오.
```python
dan = list(range(2, 9))
```
출력 결과   
<center>

![image.png]()

</center>

##문제 14
아래 보인 리스트, `lst`의 모든 요소가 리스트입니다. 모든 요소가 출력되도록 하는 코드를 작성하시오.
```python
lst = [ [1, 2, '해운대'], [3, 4, 5, 6], ['구숙정', '장만옥'] ]
```
출력 결과  
<center>

![image.png]()

</center>

##문제 15
아래 보인 리스트, `lst`의 모든 요소가 리스트입니다. `lst`의 요소(리스트)의 요소를 요소로 하는 새로운 리스트, `nlist`를 생성하는 코드를 작성하세요.
```python
lst = [ [1, 2, '해운대'], [3, 4, 5, 6], ['구숙정', '장만옥'], ['\n', '\t'] ]
```


```python
rlst = [1, 2, '해운대', 3, 4, 5, 6, '구숙정', '장만옥' ]
```

## 문제 16
다음 코드에는 리스트, `a_lst`, `b_lst`, `c_lst`가 있습니다.

```python
a_lst = [1, 2, 3]
b_lst = ['boy', 'good', 3.1415]
c_list = [ a_lst, ['역삼역', '우영우']]
```
세 리스트, `a_lst`, `b_lst`, `c_lst`의 각 요소를 요소로 하는 새로운 리스트, `nlst` 를 생성하는 코드를 작성하세요.

```python
nlst = [ 1, 2, 3, 'boy', 'good', 3.1415, [1, 2, 3], ['역삼역', '우영우'] ]
```

##문제 17

주어진 리스트, `a`를 이용하여 다음과 같은 새로운 리스트, `nlst`를 생성하는 코드를 작성하시오.
```python
a = [1, 2, 3]
```

```python
nlst = [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3,1, 2, 3]
```
`nlst`는 `a`의 요소들로 9번 반복해서 나타나는 형태입니다.

##문제 18
아래 코드에 보이는 리스트, `prices`는 달러로 표시되어 있습니다. `price`의 금액을 다 더하면 몇 달러인지와 원화로 환산하면 얼마인지 출력하는 코드를 작성하세요. (2023년 5월 28일 기준 1달러는 1,328원입니다.)

```python
prices = ['2,000$', '3,000$', '5,000$']
exchange_rate = 1328
```

## 문제 19
아래와 같이 딕셔너리 형 데이터, `person`에서 이름(`name`)과 나이(`age`)의 값을 출력하는 코드를 작성하시오.

```python
person = {
    'name':'손홍민',
    'address': '경기도 화성시 동탄',
    'age': 20,
}
```

## 문제 20
아래 코드에 보인 딕셔너리 형, `person`의 모든 Key에 대한 값을 출력하는 코드를 작성하시오.

```python
person = {
    'name':'전우치',
    'address': '경기도 화성시 동탄',
    'age': 27,
    'car': ['sedan', 'suv']
}
```

```python
# 아래와 같이 코딩하자는 의도가 아닙니다. ^^
print(person['name'], person['address'], person['age'], person['car'])
```

##문제 21
아래와 같이 파이썬 딕셔너리 형, `my_dic`를 생성했습니다.

```python
my_dic = {
    'boy': ['소년', '남자 아이', '(어린)아들'],
    'girl': ['소녀', '여자 아이', '딸'],
    'computer': {
        'cpu': '중앙처리장치',
        'memory':'기억장치'
    },
    0:'영',
    1:'하나',
    2:'둘',   
}
```
아래 코드를 한 줄만 수정해서 새로운 요소(항목)을 추가하고 싶습니다. 추가하고 싶은 요소의 키(key)는 `'good'`이며 값(value)는 `'좋아 좋아'`입니다.

```python
my_dic[] =

for key, value in my_dic.items():
  print(key, value)
```

## 문제 22
아래와 같이 파이썬 딕셔너리 형, `my_dic`를 생성했습니다.
```python
my_dic = {
    'boy': ['소년', '남자 아이', '(어린)아들'],
    'girl': ['소녀', '여자 아이', '딸'],
    'computer': {
        'cpu': '중앙처리장치',
        'memory':'기억장치'
    },
}
```

키(key), `'boy'`의 값(value)은 리스트 형 데이터입니다. 키, `'boy'`에 해당하는 값(value)에 요소를 추가하고 싶습니다. `'boy'`에 대한 값이 `['소년', '남자 아이', '(어린)아들', '(어디 출신) 사람']`이 되도록 코드를 작성하세요.

## 문제 23
아래와 같이 파이썬 딕셔너리 형, `my_dic`를 생성했습니다.
```python
my_dic = {
    'boy': ['소년', '남자 아이', '(어린)아들'],
    'girl': ['소녀', '여자 아이', '딸'],
    'computer': {
        'cpu': '중앙처리장치',
        'memory':'기억장치'
    },
}
```

키(key), `'boy'`의 값(value)은 리스트 형 데이터입니다. 키, `'boy'`에 해당하는 값(value)에 요소를 추가하고 싶습니다. `'boy'`에 대한 값이 `['소년', '남자 아이', '(어디 출신) 사람','(어린)아들']`이 되도록 코드를 작성하세요.

##문제 24

아래와 같이 파이썬 딕셔너리 형, `my_dic`를 생성했습니다. 그리고 아래 코드를 실행했을 때 다음과 같은 출력이 나오도록 코드를 완성하십시오. 주석 `#여기에 한 줄 코드` 위치에 한 줄로 코드를 작성하세요.

```python
my_dic = {
    'boy': ['소년', '남자 아이', '(어린)아들'],
    'girl': ['소녀', '여자 아이', '딸'],
    'microcontroller': {
        'cpu': '중앙처리장치',
        'memory':'기억장치',
        'peripheral':['adc', 'uart', 'pwm'],
    },
}

# 여기에 한 줄 코드

print(my_dic['microcontroller']['peripheral'])
```

출력
<center>

![image.png]()

</center>

## 문제 25

1부터 N까지의 양의 정수를 더하는데 그 합이 1000이상에 도달했을 때의 N은 얼마인지 구하는 코드를 작성하되 `while`문을 사용하세요.

##문제 26
다음과 같이 리스트, `lst`를 생성하였습니다. `lst`의 요소에서 `1`을 모두 제거하는 코드를 작성하세요.

```python
import random

lst = []
lst += random.sample([1, 2, 3], 2)
lst += random.sample([1, 2, 3], 2)
lst += random.sample([1, 2, 3], 2)
lst += random.sample([1, 2, 3], 2)
```

##문제 27
아래 코드에 보인 리스트 `banks`의 요소에서 '기업은행'을 모두 삭제하는 코드를 작성하세요.

```python
import random

lst = []
lst += random.sample([0, 1, 2, 3], 2)
lst += random.sample([0, 1, 2, 3], 2)
lst += random.sample([0, 1, 2, 3], 2)
lst += random.sample([0, 1, 2, 3], 2)


lst_bank = ['기업은행', '제일은행', '우리은행', '국민은행']

banks=[]

for idx in lst:                # lst = [0, 1, 0, 3, 2, 3, 1, 2]
  banks.append(lst_bank[idx])

print(banks)
```

## 문제 28
길이가 23cm이상이고 무게는 250g이상인 생선은 '쿨러에 담는다'고 출력하고 기준에 미달되는 생선은 '방생'이라고 출력합니다.

```python
fish_length = [14, 15.5, 13.5, 23.5, 28.5, 26.0, 12, 32, 29, 14.5]
fish_weight = [100, 150, 140, 250, 300, 280, 80, 315, 220, 90]
```

* (1) 반복 동작을 `for`문으로 구현하십시오.
* (2) 반복 동작을 `while`문으로 구현하십시오.

##문제 29
아래 코드를 실행 시켰을 때 다음과 같이 출력 되도록 코드를 완성하시오.

```python
my_name = ('kim', 'sung pil')

(first_name, last_name) =
print(last_name, first_name)
```

##문제 30
리스트, `lst`의 최대값, 최소값, 총합을 구하려고 한다. 그리고 평균값을 구하려고 합니다. 아래 코드를 완성하시오.

```python
lst = [ -2, -1, 0, 1, 2, 3]
print('리스트, lst 요소들 중 최대값 :', )
print('리스트, lst 요소들 중 최소값 :', )
print('리스트, lst 요소들의 합 :', )
print('리스트, lst 요소들의 평균값 :', )
```

## 문제 31
다음 코드에서`lst_banks`의 요수의 값이 '기업은행'일 때 인덱스 값을 출력하는 코드를 작성하시오.

```python
import random

banks = ['국민은행', '기업은행', '우리은행', '제일은행', '신한은행']

lst_banks = []
lst_banks += random.sample(banks, 2)
lst_banks += random.sample(banks, 2)
lst_banks += random.sample(banks, 2)
lst_banks += random.sample(banks, 2)
```

## 문제 32
아래 보인 코드에서 리스트, `lst`를 활용하여 리스트 `rlst`와 같이 값으로 변경 되도록 리스트 내포를 활용한 코드를 작성하시오.

```python
lst = list( range(1, 9, 2) )
rlst = [ ]
print(rlst)
```

<center>

![image.png]()
</center>

##문제 33
1부터 10까지 양의 정수를 요소로 하는 리스트, `lst`가 있습니다. `lst`의 요소가 짝수이면 `True` 홀수이면 `False'를 값으로 하는 리트스, `rlst`를 생설하려고 합니다. 리스트 내포를 활용하여 코드를 완성하시오.

```python
lst = list(range(1, 11))
rlst = []
print(rlst)
```

##문제 34
1부터 10까지 양의 정수에서 짝수이면 True라고 판단하고 홀수이면 False로 판단하여 판단 결과를 값으로 하는 리트스,`rlst`를 생성하려고 합니다. 리스트 내포를 활용하여 한 줄 코드로 작성하시오.

```python
rlst = []
print(rlst)
```

##문제 35
변수 $x$의 범위는 1부터 15까지 양의 정수입니다.
$$y = 2x + 3$$
변수 $y$의 값을 리스트 형태로 보관하고 싶습니다. 그런데 이 때 $x$의 값이 5일 때와 11일 때는 제외하고 싶습니다.

##문제 36
1부터 15까지의 양의 정수 범위에서 3의 배수인 경우는 문자열,'3의 배수' 그 외 경우는 나머지 값을 요소로 하는 리스트를 생성하는 코드를 작성하시오. 출력 결과는 다음과 같습니다.

<center>

![image.png]()

</center>

##문제 37

아래 코드의 데이터를 활용하여 하나의 문자열 데이터 `'2023-06-11'`를 생성하는 코드를 작성하시오.

```python
year = '2023'
month = '06'
day = '11'
```

##문제 38
```python
for 반복자 in 반복할_수_있는_것:
  #statement(문장)
```

위 코드에서 `반복할_수_있는_것`을 프로그래밍 용어로 **이터러블(iterable)**이라고 합니다. 즉 이터러블은 내부에 있는 요소를 하나씩 꺼낼 수 있는 객체를 의미합니다. 리스트, 딕셔너리, 문자열, 튜플 등은 모두 내부에서 요소를 하나씩 꺼낼 수 있으므로 이터러블입니다.

```python
numbers = [1, 2, 3, 4, 5, 6]
r_num = reversed(numbers)

print(next(r_num))
print(next(r_num))
print(next(r_num))
print(next(r_num))
print(next(r_num))
print(next(r_num))
```

먼저, 위 코드의 실행 결과를 확인 후 위 코드와 동일한 동작을 하도록 아래 코드를 완성하시오.